fix worktree-add helper to do jj things again

diff --git a/tools/worktree-add b/tools/worktree-add
--- a/tools/worktree-add
+++ b/tools/worktree-add
@@ -13,17 +13,26 @@ after_worktrees=$(git worktree list --porcelain | grep worktree | cut -d' ' -f2)
 
 # Find the new worktree path
 new_worktree_path=$(comm -13 <(echo "$before_worktrees" | sort) <(echo "$after_worktrees" | sort))
+new_worktree_base=$(basename "$new_worktree_path")
+new_worktree_rev=$(git -C "$new_worktree_path" rev-parse HEAD)
 
 if [ -d "$new_worktree_path" ]; then
-    git -C "$new_worktree_path" submodule update --init --recursive
+    git -C "$new_worktree_path" submodule update --init --recursive || echo "WARNING: submodule init failed; you'll have to try again later!"
 fi
 
-# Initialize a jj repo in the new worktree
-# if command -v jj >/dev/null; then
-#     pushd "$new_worktree_path" >> /dev/null
-#     jj git init --git-repo . .
-#     popd >> /dev/null
-# fi
+# Create the jj workspace so we can steal the workspace's linkage to our root .jj
+if command -v jj > /dev/null; then
+    shopt -s dotglob
+    # Temporarily get the worktree out of the way, or we can't make our workspace
+    TEMPPATH=$(mktemp -d -u)
+    trap "rm -rf $TEMPPATH" EXIT
+    mv "$new_worktree_path" $TEMPPATH
+    # Honor any commit-ish passed to `git worktree add`
+    jj workspace add -r "$new_worktree_rev" "../$new_worktree_base"
+    cp -r "$TEMPPATH"/* "$new_worktree_path"/
+    shopt -u dotglob
+    echo "/*" > "$new_worktree_path/.jj/.gitignore"
+fi
 
 # Our worktree directory pattern is
 # /path/to/project
